#
#  MIT License
#
#  Copyright (c) 2020 engineer365.org
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#  SOFTWARE.

version: '2.2'


networks:
  default:


services:

  mysql-master:
    container_name: mysql-master
    image: mysql:8.0.22
    environment: 
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=playground
      - MYSQL_USER=playground_user
      - MYSQL_PASSWORD=playground_password
    restart: always
    volumes:
      - /opt/mysql-master/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - /opt/mysql-master/create-fleashop.sql:/docker-entrypoint-initdb.d/create-fleashop.sql:ro
      - /data/mysql-master/work:/var/lib/mysql:rw
    ports: 
      - 3306:3306
    healthcheck:
      test: "mysql --user=playground_user --password=playground_password -D playground --execute \"SHOW TABLES;\""
      interval: 3s
      timeout: 1s
      retries: 60
  
